-- AlterTable
ALTER TABLE `ChartEvent` MODIFY `type` ENUM('PAGE_VIEW', 'PRODUCT_VIEW', 'PRODUCT_IMAGE_VIEW', 'ADD_TO_CART', 'REMOVE_FROM_CART', 'SIZE_SELECTED', 'CHECKOUT_CLICKED', 'CHECKOUT_CREATED', 'CHECKOUT_ITEM') NOT NULL;
